// Creating playground constants
export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';

// my playgrounds constants
export const BOOKINGS_LIST_MY_REQUEST = 'BOOKINGS_LIST_MY_REQUEST';
export const BOOKINGS_LIST_MY_SUCCESS = 'BOOKINGS_LIST_MY_SUCCESS';
export const BOOKINGS_LIST_MY_FAIL = 'BOOKINGS_LIST_MY_FAIL';
export const BOOKINGS_LIST_MY_RESET = 'BOOKINGS_LIST_MY_RESET';

// Updating playground constant
export const BOOKING_APPROVE_REQUEST = 'BOOKING_APPROVE_REQUEST';
export const BOOKING_APPROVE_SUCCESS = 'BOOKING_APPROVE_SUCCESS';
export const BOOKING_APPROVE_FAIL = 'BOOKING_APPROVE_FAIL';
export const BOOKING_APPROVE_RESET = 'BOOKING_APPROVE_RESET';

// Getting playgrounds constants
export const PLAYGROUND_BOOKINGS_LIST_REQUEST =
  'PLAYGROUND_BOOKINGS_LIST_REQUEST';
export const PLAYGROUND_BOOKINGS_LIST_SUCCESS =
  'PLAYGROUND_BOOKINGS_LIST_SUCCESS';
export const PLAYGROUND_BOOKINGS_LIST_FAIL = 'PLAYGROUND_BOOKINGS_LIST_FAIL';
