// Getting complaints constants
export const COMPLAINT_LIST_REQUEST = 'COMPLAINT_LIST_REQUEST';
export const COMPLAINT_LIST_SUCCESS = 'COMPLAINT_LIST_SUCCESS';
export const COMPLAINT_LIST_FAIL = 'COMPLAINT_LIST_FAIL';

// Getting single complaint constants
export const COMPLAINT_DETAILS_REQUEST = 'COMPLAINT_DETAILS_REQUEST';
export const COMPLAINT_DETAILS_SUCCESS = 'COMPLAINT_DETAILS_SUCCESS';
export const COMPLAINT_DETAILS_FAIL = 'COMPLAINT_DETAILS_FAIL';

// Creating complaint constants
export const COMPLAINT_CREATE_REQUEST = 'COMPLAINT_CREATE_REQUEST';
export const COMPLAINT_CREATE_SUCCESS = 'COMPLAINT_CREATE_SUCCESS';
export const COMPLAINT_CREATE_FAIL = 'COMPLAINT_CREATE_FAIL';
export const COMPLAINT_CREATE_RESET = 'COMPLAINT_CREATE_RESET';

// Creating Complaint comment
export const COMPLAINT_CREATE_COMMENT_REQUEST =
  'COMPLAINT_CREATE_COMMENT_REQUEST';
export const COMPLAINT_CREATE_COMMENT_SUCCESS =
  'COMPLAINT_CREATE_COMMENT_SUCCESS';
export const COMPLAINT_CREATE_COMMENT_FAIL = 'COMPLAINT_CREATE_COMMENT_FAIL';
export const COMPLAINT_CREATE_COMMENT_RESET = 'COMPLAINT_CREATE_COMMENT_RESET';

// my complaints constants
export const COMPLAINT_LIST_MY_REQUEST = 'COMPLAINT_LIST_MY_REQUEST';
export const COMPLAINT_LIST_MY_SUCCESS = 'COMPLAINT_LIST_MY_SUCCESS';
export const COMPLAINT_LIST_MY_FAIL = 'COMPLAINT_LIST_MY_FAIL';
export const COMPLAINT_LIST_MY_RESET = 'COMPLAINT_LIST_MY_RESET';

// Updating complaint constant
export const COMPLAINT_UPDATE_REQUEST = 'COMPLAINT_UPDATE_REQUEST';
export const COMPLAINT_UPDATE_SUCCESS = 'COMPLAINT_UPDATE_SUCCESS';
export const COMPLAINT_UPDATE_FAIL = 'COMPLAINT_UPDATE_FAIL';
export const COMPLAINT_UPDATE_RESET = 'COMPLAINT_UPDATE_RESET';
