// Creating playground constants
export const PLAYGROUND_CREATE_REQUEST = 'PLAYGROUND_CREATE_REQUEST';
export const PLAYGROUND_CREATE_SUCCESS = 'PLAYGROUND_CREATE_SUCCESS';
export const PLAYGROUND_CREATE_FAIL = 'PLAYGROUND_CREATE_FAIL';
export const PLAYGROUND_CREATE_RESET = 'PLAYGROUND_CREATE_RESET';

// my playgrounds constants
export const PLAYGROUND_LIST_MY_REQUEST = 'PLAYGROUND_LIST_MY_REQUEST';
export const PLAYGROUND_LIST_MY_SUCCESS = 'PLAYGROUND_LIST_MY_SUCCESS';
export const PLAYGROUND_LIST_MY_FAIL = 'PLAYGROUND_LIST_MY_FAIL';
export const PLAYGROUND_LIST_MY_RESET = 'PLAYGROUND_LIST_MY_RESET';

// Updating playground constant
export const PLAYGROUND_APPROVE_REQUEST = 'PLAYGROUND_APPROVE_REQUEST';
export const PLAYGROUND_APPROVE_SUCCESS = 'PLAYGROUND_APPROVE_SUCCESS';
export const PLAYGROUND_APPROVE_FAIL = 'PLAYGROUND_APPROVE_FAIL';
export const PLAYGROUND_APPROVE_RESET = 'PLAYGROUND_APPROVE_RESET';

// Getting playgrounds constants
export const PLAYGROUND_LIST_REQUEST = 'PLAYGROUND_LIST_REQUEST';
export const PLAYGROUND_LIST_SUCCESS = 'PLAYGROUND_LIST_SUCCESS';
export const PLAYGROUND_LIST_FAIL = 'PLAYGROUND_LIST_FAIL';
